### ISSUE TITLE
tinkers tools.

### ISSUE THREAD

**Issue by katmac34** [Mattabase/Wastelands-Issues#3]
im at the stage of tinkers tools in the smeltery.. theres seems to be some issue with the materials needed.. i placed 6 eeralds in the smeltery for 2 tools.. the axe and the yo-yo.. once the cast was made. i poured the emerald.. but only used 2 of the 6 for the parts

**Comment by katmac34** [comment]
after further testing. so far it only seems to be 1 ingot used on emerald. iron uses the normal amount and so does gold

**Comment by Mattabase** [comment]
Issue appears to be on the mod side. Taking a look.
