### ISSUE TITLE
several things

### ISSUE THREAD

**Issue by katmac34** [Mattabase/Wastelands-Issues#7]
so over the past 2 or so days i've made a small list of little problems. firstly the exp for leveling resets everytime you log in/out.. for me it crashes the pack shortly after i put exp into any skill.

also the yo-yo, it has a bug where if it catches on an object when returning and gets caught for a short time then quickly returns.. it destroys the items on the yo-yo if you have the collect modifier (https://clips.twitch.tv/ElegantCoyPangolinTwitchRaid)

**Comment by Mattabase** [comment]
Split into Issue #8 and #9
